cat /etc/resolv.conf #cat obriga o arquivo aparecer o configuraçao aparecer no terminal

  ##no erro/divergencia...,alterrar conf manialmente 
  
  echo "nameserver 9.9.9.9" > /etc/resolv.conf
  echo "nameserver 1.1.1.1" >> /etc/resolv.conf

    apk add openresolv

      rc-service networking restart

        ping -c 5 google.com
